### ISSUE TITLE
Merge Scenes

### ISSUE THREAD

**Issue by jeyemwey** [huggingface/gsplat.js#40]
I want to add dynamic content, such as arrows, markers etc. into the scene.

For this reason, I have written code that will build a synthetic scene which contains a cube, a triangle etc by filling a boundary with splats. I can modify the new scene (scaling, translating, ...) to my liking.
Next, I want to "add" the splats to the existing world, and, ideally, modify the positions of the subscene after they were added to the scene. Do you have an idea, how we can process this? Ideally, the subscene would just use a portion of the `_data` buffer from the larger scene, but I'm not sure if that's possible in JS.

**Comment by dylanebert** [comment]
I have refactored the `Scene` class by separating out the render data packing into `renderers/webgl/utils/RenderData`.

Now, you only need to worry about manipulating the positions, rotations, scales, and color matrices directly, which should make a future update for editing tools much easier.
