### ISSUE TITLE
Scripts for convert `.ply` file into `.splat` file

### ISSUE THREAD

**Issue by Srameo** [huggingface/gsplat.js#43]
Hello, thank you for your excellent work! 

However, I would like to know if there is a Python or shell script that can quickly convert `.ply` files to `.splat` files?

**Comment by oseiskar** [comment]
You could try our Python tools https://github.com/SpectacularAI/point-cloud-tools (disclaimer: I represent _Spectacular AI_ and we are not connected to this repository in any way):

```bash
# --- Install
git clone https://github.com/SpectacularAI/point-cloud-tools
cd point-cloud-tools
# optional but recommended: activate a virtual environment at this point
pip install -r requirements.txt

# --- Convert
python convert.py \
    /PATH/TO/bonsai/point_cloud/iteration_30000/point_cloud.ply \
    /OUT/PATH/bonsai.splat \
   --ply_input_format=inria
```
Note that the Gaussian Splatting community is yet to agree how the color data is stored in the PLY file. Therefore you need to specify that manually. See the README for more info.

Extra tip / advertisement: You can also our tools to create the PLY files using your phone and Nerfstudio, without uploading your data to a cloud of any kind. [See here for more info](https://docs.nerf.studio/quickstart/custom_dataset.html#spectacularai).

**Comment by Srameo** [comment]
Thank you for your reply, this script is very effective!

**Comment by dylanebert** [comment]
I can add that!

**Comment by kungfooman** [comment]
> I can add that!

That would be a great relief! There are so many formats and every tool wants something else... compressed, uncompressed, special-this, special-that, ply, splat etc. :see_no_evil:

**Comment by oseiskar** [comment]
Note that the PLY files created by Inria code or Nerfstudio typically contain more information than `.splat`, in particular, the full spherical harmonic coefficients that capture the direction dependencies in lighting. The current `.splat` format only has flat colors. So the conversion PLY -> splat -> PLY loses information (which may or may not be relevant to your use case)

**Comment by showpixelVR** [comment]
What if i do import a ply first, wouldnt it keep the sh on plyexport?

**Comment by dylanebert** [comment]
Done! #52
