### ISSUE TITLE
I don't need to load loading and onProgress，When data is loaded, how can I render it on the interface immediately?

### ISSUE THREAD

**Issue by did66** [huggingface/gsplat.js#47]
I don't need to load loading，When data is loaded, how can I render it on the interface immediately? I see Class Loader

Nothing's been done there

**Comment by dylanebert** [comment]
What?

**Comment by did66** [comment]
> What?

For example, when the splat file is fetch 50%, the page needs to display the 50% data.

**Comment by did66** [comment]
> What?
![1](https://github.com/huggingface/gsplat.js/assets/15080963/72528bc0-9cda-47b2-8ad1-7be07e277e3d)

The function of this part of the code

**Comment by dylanebert** [comment]
Oh I see, thanks. I've added it as a new feature issue in #55
