### ISSUE TITLE
Replacing PLYLoaders with file type checking in the Loaders class

### ISSUE THREAD

**Issue by TravisThomp** [huggingface/gsplat.js#58]
Doesn't really seem necessary to have two separate loaders for `.splat`, and `.ply`. The Loaders logic could just check the url file extension and perform the necessary actions for the ply data loading. It would make the user experience a little simpler. LMK if you disagree.

**Comment by dylanebert** [comment]
That makes sense, I can start to migrate it with a deprecation warning in the next update

**Comment by mateusz-malicki** [comment]
I dont think that relying on URL suffix or file name or MIME type is good idea.

1. file name can be just some UUID/GUID string or can look like this `/files(model.splat)` or like this  `/files(model.splat)/$raw` or anything else, why loader should have preferences about URL format?
2. Same argument for case when we are loading model from file
3. What about loading model from ReadableStream, Response, ArrayBuffer, Blob, or anything that can store/stream binary data?
