### ISSUE TITLE
How to render from a set of camera position?

### ISSUE THREAD

**Issue by vahidEtt** [huggingface/gsplat.js#64]
Hi, I am trying to render the scene from a set of camera position/rotation that I load from a JSON file.

I think the right way is first to disable the "orbitControls" (engine.orbitControls.enabled = false;) and then set the camera position/rotation manually like this:  'camera.data.update(position, rotation);'. Am I right?

Any suggestion/recommendation is welcome!

**Comment by dylanebert** [comment]
You can simply not create or update the orbit controls :)

And then you should just be able to specify:
`camera.position =`
`camera.rotation = `
before rendering

Check out the camera update example: https://github.com/huggingface/gsplat.js/blob/main/examples/camera-updates/src/main.ts
